<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cit by cit_id
     */
    function get_cit($cit_id)
    {
        return $this->db->get_where('cit',array('cit_id'=>$cit_id))->row_array();
    }
        
    /*
     * Get all cit
     */
    function get_all_cit()
    {
        $this->db->order_by('cit_id', 'desc');
        return $this->db->get('cit')->result_array();
    }
        
    /*
     * function to add new cit
     */
    function add_cit($params)
    {
        $this->db->insert('cit',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cit
     */
    function update_cit($cit_id,$params)
    {
        $this->db->where('cit_id',$cit_id);
        return $this->db->update('cit',$params);
    }
    
    /*
     * function to delete cit
     */
    function delete_cit($cit_id)
    {
        return $this->db->delete('cit',array('cit_id'=>$cit_id));
    }
}
