<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_moua_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_moua by m_moua_id
     */
    function get_m_moua($m_moua_id)
    {
        return $this->db->get_where('m_moua',array('m_moua_id'=>$m_moua_id))->row_array();
    }
        
    /*
     * Get all m_moua
     */
    function get_all_m_moua()
    {
        $this->db->order_by('m_moua_id', 'desc');
        return $this->db->get('m_moua')->result_array();
    }
        
    /*
     * function to add new m_moua
     */
    function add_m_moua($params)
    {
        $this->db->insert('m_moua',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_moua
     */
    function update_m_moua($m_moua_id,$params)
    {
        $this->db->where('m_moua_id',$m_moua_id);
        return $this->db->update('m_moua',$params);
    }
    
    /*
     * function to delete m_moua
     */
    function delete_m_moua($m_moua_id)
    {
        return $this->db->delete('m_moua',array('m_moua_id'=>$m_moua_id));
    }
}
