<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_mutual_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_mutual by m_mut_id
     */
    function get_m_mutual($m_mut_id)
    {
        return $this->db->get_where('m_mutual',array('m_mut_id'=>$m_mut_id))->row_array();
    }
        
    /*
     * Get all m_mutual
     */
    function get_all_m_mutual()
    {
        $this->db->order_by('m_mut_id', 'desc');
        return $this->db->get('m_mutual')->result_array();
    }
        
    /*
     * function to add new m_mutual
     */
    function add_m_mutual($params)
    {
        $this->db->insert('m_mutual',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_mutual
     */
    function update_m_mutual($m_mut_id,$params)
    {
        $this->db->where('m_mut_id',$m_mut_id);
        return $this->db->update('m_mutual',$params);
    }
    
    /*
     * function to delete m_mutual
     */
    function delete_m_mutual($m_mut_id)
    {
        return $this->db->delete('m_mutual',array('m_mut_id'=>$m_mut_id));
    }
}
