<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_partner_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_partner by m_par_id
     */
    function get_m_partner($m_par_id)
    {
        return $this->db->get_where('m_partner',array('m_par_id'=>$m_par_id))->row_array();
    }
        
    /*
     * Get all m_partner
     */
    function get_all_m_partner()
    {
        $this->db->order_by('m_par_id', 'desc');
        return $this->db->get('m_partner')->result_array();
    }
        
    /*
     * function to add new m_partner
     */
    function add_m_partner($params)
    {
        $this->db->insert('m_partner',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_partner
     */
    function update_m_partner($m_par_id,$params)
    {
        $this->db->where('m_par_id',$m_par_id);
        return $this->db->update('m_partner',$params);
    }
    
    /*
     * function to delete m_partner
     */
    function delete_m_partner($m_par_id)
    {
        return $this->db->delete('m_partner',array('m_par_id'=>$m_par_id));
    }
}
