<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_place_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_place by m_pla_id
     */
    function get_m_place($m_pla_id)
    {
        return $this->db->get_where('m_place',array('m_pla_id'=>$m_pla_id))->row_array();
    }
        
    /*
     * Get all m_place
     */
    function get_all_m_place()
    {
        $this->db->order_by('m_pla_id', 'desc');
        return $this->db->get('m_place')->result_array();
    }
        
    /*
     * function to add new m_place
     */
    function add_m_place($params)
    {
        $this->db->insert('m_place',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_place
     */
    function update_m_place($m_pla_id,$params)
    {
        $this->db->where('m_pla_id',$m_pla_id);
        return $this->db->update('m_place',$params);
    }
    
    /*
     * function to delete m_place
     */
    function delete_m_place($m_pla_id)
    {
        return $this->db->delete('m_place',array('m_pla_id'=>$m_pla_id));
    }
}
