<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stum by sta_id
     */
    function get_stum($sta_id)
    {
        return $this->db->get_where('sta',array('sta_id'=>$sta_id))->row_array();
    }
        
    /*
     * Get all sta
     */
    function get_all_sta()
    {
        $this->db->order_by('sta_id', 'desc');
        return $this->db->get('sta')->result_array();
    }
        
    /*
     * function to add new stum
     */
    function add_stum($params)
    {
        $this->db->insert('sta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update stum
     */
    function update_stum($sta_id,$params)
    {
        $this->db->where('sta_id',$sta_id);
        return $this->db->update('sta',$params);
    }
    
    /*
     * function to delete stum
     */
    function delete_stum($sta_id)
    {
        return $this->db->delete('sta',array('sta_id'=>$sta_id));
    }
}
